[versions]
junit = "5.11.3"
junitPlatform = "1.11.3"

[libraries]
junitJupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatform" }

[bundles]
junit = ["junitJupiter", "junitPlatformLauncher"]
